name: filipay_beta
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  crypto: ^3.0.3
  encrypt: ^5.0.3
  art_sweetalert: ^0.0.5
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_local_authentication: ^1.2.0
  local_auth: ^2.2.0
  gradient_borders: ^1.0.0
  hive_flutter: ^1.1.0
  image_picker: ^1.0.7
  intl: ^0.19.0
  pin_code_fields: ^8.0.1
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  slider_button: ^2.1.0
  text_divider: ^1.0.0
  time_range: ^1.1.0

# flutter_launcher_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/general/filipay-logo.png"
dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/general/
    - assets/transportation/
    - assets/e-wallet/

fonts:
  - family: Schyler
    fonts:
      - asset: fonts/Schyler-Regular.ttf
      - asset: fonts/Schyler-Italic.ttf
        style: italic
  - family: Trajan Pro
    fonts:
      - asset: fonts/TrajanPro.ttf
      - asset: fonts/TrajanPro_Bold.ttf
        weight: 700
